Port tests from cannon.js
pmndrs/cannon-es pull request #50
Opened 2020-10-19 18:41 UTC by patreeceeo

Addresses #49. Just did Narrowphase for now, but hope to do a lot more!

I added `jest --onlyChanged` to the pre-commit hook just as an idea. I find it helpful in my projects, but I get it if it's not how y'all want to work.

2020-10-19 18:43 UTC, patreeceeo commented on src/equations/ContactEquation.ts
> +   */
Turned these comments into JSDoc comments, which is helpful if using intellisense, especially with the terse names.

2020-10-19 18:47 UTC, patreeceeo commented on src/world/Narrowphase.test.ts
> +    // as using `new ContactMaterial()` for cg.currentContactMaterial.
There was a line here from the original which constructed a ContactMaterial using a zero-arg constructor which doesn't exist. Narrowphases assigns itself a default contact material, so perhaps removing this line doesn't effect the test?

2020-10-20 15:28 UTC, marcofugaro commented on src/equations/ContactEquation.ts
> +   */
I agree, we should convert all of the parameters comments back to their JSDoc form, since otherwise we won't even be able to generate documentation about them, see this issue of #14

But maybe let's do this in another PR?

<img src="https://user-images.githubusercontent.com/7217420/96608352-90c63e80-12f9-11eb-966a-daf6832f4435.png" width="400" />

2020-10-20 15:40 UTC, patreeceeo commented on src/equations/ContactEquation.ts
> +   */
Sounds good!

2020-10-20 15:50 UTC, marcofugaro requested changes

2020-10-20 15:50 UTC, marcofugaro commented on dist/cannon-es.js
> +  sphereSphere(si, sj, xi, xj, _, __, bi, bj, rsi, rsj, justTest) {
please leave them with the original names, even if they're not used

2020-10-20 15:50 UTC, marcofugaro commented on package.json
> +    "jest": "^26.6.0"
these are `devDependencies`, add them there

2020-10-20 15:50 UTC, marcofugaro commented on package.json
> +      "pre-commit": "pretty-quick && jest --onlyChanged"
```suggestion
      "pre-commit": "pretty-quick"
```

I wouldn't run them on the git commit, people might want to commit work in progress stuff.

Please add a `test` script for now

2020-10-20 15:50 UTC, marcofugaro commented on src/world/Narrowphase.test.ts
> +    // as using `new ContactMaterial()` for cg.currentContactMaterial.
yeah I agree, I think it's fine. Could you instead rename `cg` to something more exhaustive? 

I know it's `cg` in the original tests, but I don't even know what it means 😅

2020-10-20 15:51 UTC, marcofugaro commented on dist/cannon-es.js
> +  sphereSphere(si, sj, xi, xj, _, __, bi, bj, rsi, rsj, justTest) {
oh this is the generated file, I meant to comment on the file in `src/`

2020-10-20 15:52 UTC, marcofugaro commented on src/world/Narrowphase.test.ts
> +    // as using `new ContactMaterial()` for cg.currentContactMaterial.
yeah I agree, I think it's fine. Could you instead rename `cg` to something more exhaustive? 

I know it's `cg` in the original tests, but I don't even know what it means 😅

2020-10-20 16:12 UTC, patreeceeo commented on src/world/Narrowphase.test.ts
> +    // as using `new ContactMaterial()` for cg.currentContactMaterial.
I was speculating maybe it stood for Contact Generator? but 🤷

2020-10-20 16:16 UTC, patreeceeo commented
Was wondering how, when I run `yarn` with no arguments, it knows to do all the build steps? That might be a good place to include the tests (in addition to having a "test" script)?

2020-10-20 16:44 UTC, marcofugaro commented
Yeah it makes sense, [react-spring is already doing it](https://github.com/pmndrs/react-spring/blob/29206643f08500f929655c254410626ab1482db2/package.json#L35].

It's from the same organization so we follow the same conventions.

2020-10-22 02:14 UTC, codynova approved these changes
This looks good. Thank you very much for the contribution, and thank you to @marcofugaro for the reviews 🥇

2020-10-22 02:15 UTC, merged